---
- name: unzip installed
  yum:
    name: unzip
    state: present

- name: terraform installed
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/terraform
