---
- name: user exists
  become: yes
  user:
    name: abyss
    state: present
    generate_ssh_key: yes
    append: yes
    groups:
      - wheel

- name: dotfiles installed from git
  become: yes
  become_user: abyss
  git:
    repo: https://github.com/abyss/dotfiles
    dest: /home/abyss/dotfiles

- name: check if dotfiles installed
  become: yes
  become_user: abyss
  stat:
    path: /home/abyss/.bashrc
    follow: no
  register: bashrc

- name: install dotfiles
  become: yes
  become_user: abyss
  shell: /home/abyss/dotfiles/install.sh
  when: not (bashrc.stat.islnk is defined and bashrc.stat.islnk)

- name: authorized_keys updated
  become: yes
  become_user: abyss
  get_url:
    url: https://keys.abyss.dev
    dest: /home/abyss/.ssh/authorized_keys
    force: yes
    mode: 0600
